"""initial database schema

Revision ID: 62c4e5bf6b56
Revises: 
Create Date: 2026-10-05 17:31:56.470800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c4e5bf6b56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('u1_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('google_subject', sa.String(length=255), nullable=True),
    sa.Column('microsoft_subject', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('security_question', sa.Text(), nullable=True),
    sa.Column('security_answer_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_subject'),
    sa.UniqueConstraint('microsoft_subject'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_u1_id'), ['u1_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('mfa_factor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mfa_factor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_factor_user_id'), ['user_id'], unique=False)

    op.create_table('profile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_user_id'), ['user_id'], unique=True)

    op.create_table('recovery_code',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.Text(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_code_code_hash'), ['code_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_recovery_code_user_id'), ['user_id'], unique=False)

    op.create_table('session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_token_hash', sa.Text(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_session_token_hash'), ['session_token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_session_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_user_id'), ['user_id'], unique=False)

    op.create_table('team',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=20), nullable=False),
    sa.Column('team_display_name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('live_access_status', sa.String(length=30), nullable=False),
    sa.Column('live_access_granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_live_access_status'), ['live_access_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_team_id'), ['team_id'], unique=True)

    op.create_table('application',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('authorized_primary_url', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detection_state', sa.JSON(), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('webhook_secret_hash', sa.Text(), nullable=True),
    sa.Column('webhook_secret_prefix', sa.String(length=32), nullable=True),
    sa.Column('webhook_active', sa.Boolean(), nullable=False),
    sa.Column('webhook_events', sa.JSON(), nullable=True),
    sa.Column('webhook_last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(owner_user_id IS NOT NULL AND team_id IS NULL) OR (owner_user_id IS NULL AND team_id IS NOT NULL)', name='ck_application_owner_or_team'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'slug', 'environment', name='uq_application_owner_slug_environment'),
    sa.UniqueConstraint('team_id', 'slug', 'environment', name='uq_application_team_slug_environment')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_team_id'), ['team_id'], unique=False)

    op.create_table('profile_completion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('identity_completed', sa.Boolean(), nullable=False),
    sa.Column('presentation_completed', sa.Boolean(), nullable=False),
    sa.Column('payment_verified', sa.Boolean(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('initial_completion_reward_granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_completion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_completion_profile_id'), ['profile_id'], unique=True)

    op.create_table('response_connector',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('configuration_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_connector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_connector_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_connector_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_connector_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_connector_type'), ['type'], unique=False)

    op.create_table('response_policy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('execution_mode', sa.String(length=30), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_policy_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_policy_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_policy_execution_mode'), ['execution_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_policy_team_id'), ['team_id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('default_environment', sa.String(length=20), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('security_notifications', sa.Boolean(), nullable=False),
    sa.Column('announcement_notifications', sa.Boolean(), nullable=False),
    sa.Column('privacy_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_profile_id'), ['profile_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_settings_user_id'), ['user_id'], unique=True)

    op.create_table('subscription',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('access_method', sa.String(length=30), nullable=False),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('limits', sa.JSON(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_interval', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_customer_reference', sa.String(length=255), nullable=True),
    sa.Column('provider_subscription_reference', sa.String(length=255), nullable=True),
    sa.Column('latest_payment_reference', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_next_billing_at'), ['next_billing_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_plan_code'), ['plan_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_provider_subscription_reference'), ['provider_subscription_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_team_id'), ['team_id'], unique=False)

    op.create_table('team_message',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('sender_user_id', sa.String(length=36), nullable=False),
    sa.Column('reply_to_message_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['team_message.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_message_reply_to_message_id'), ['reply_to_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_message_sender_user_id'), ['sender_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_message_team_id'), ['team_id'], unique=False)

    op.create_table('team_owner',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_owner')
    )
    with op.batch_alter_table('team_owner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_owner_assigned_by_user_id'), ['assigned_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_owner_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_owner_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_owner_user_id'), ['user_id'], unique=False)

    op.create_table('team_role',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('console_layout', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_team_role_name')
    )
    with op.batch_alter_table('team_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_role_team_id'), ['team_id'], unique=False)

    op.create_table('api_key',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=False),
    sa.Column('secret_key_hash', sa.String(length=255), nullable=False),
    sa.Column('secret_key_prefix', sa.String(length=32), nullable=False),
    sa.Column('public_scopes', sa.JSON(), nullable=True),
    sa.Column('secret_scopes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_key_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_key_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_key_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_key_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_key_public_key'), ['public_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_key_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_key_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_key_team_id'), ['team_id'], unique=False)

    op.create_table('asset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_provider', sa.String(length=50), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('analysis_status', sa.String(length=30), nullable=False),
    sa.Column('analysis_metadata', sa.JSON(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'identifier', name='uq_asset_application_identifier')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_analysis_status'), ['analysis_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_type'), ['type'], unique=False)

    op.create_table('incident',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_status'), ['status'], unique=False)

    op.create_table('subscription_application',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attached_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'application_id', name='uq_subscription_application')
    )
    with op.batch_alter_table('subscription_application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_application_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_application_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_application_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('team_invitation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('accepted_user_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['team_role.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invitation_accepted_user_id'), ['accepted_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitation_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitation_invited_by_user_id'), ['invited_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitation_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitation_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitation_token_hash'), ['token_hash'], unique=True)

    op.create_table('team_member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('team_access_enabled', sa.Boolean(), nullable=False),
    sa.Column('team_access_disabled_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_schedule', sa.JSON(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['team_role.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member_user')
    )
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_member_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_member_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_member_team_access_disabled_until'), ['team_access_disabled_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_member_team_access_enabled'), ['team_access_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_member_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_member_user_id'), ['user_id'], unique=False)

    op.create_table('team_notification_rule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('target_user_id', sa.String(length=36), nullable=False),
    sa.Column('minimum_severity', sa.String(length=30), nullable=True),
    sa.Column('event_types', sa.JSON(), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_notification_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_notification_rule_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_notification_rule_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_notification_rule_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_notification_rule_minimum_severity'), ['minimum_severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_notification_rule_target_user_id'), ['target_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_notification_rule_team_id'), ['team_id'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('detection_check', sa.String(length=150), nullable=True),
    sa.Column('verification_mode', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor_identifier', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('ix_event_application_fingerprint', ['application_id', 'fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_detection_check'), ['detection_check'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_verification_mode'), ['verification_mode'], unique=False)

    op.create_table('recovery_operation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('initiated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('operation_type', sa.String(length=150), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('verification_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_operation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_operation_actor_type'), ['actor_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_operation_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_operation_initiated_by_user_id'), ['initiated_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_operation_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_operation_status'), ['status'], unique=False)

    op.create_table('response_decision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('connector_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=150), nullable=False),
    sa.Column('execution_mode', sa.String(length=30), nullable=False),
    sa.Column('target_scope', sa.String(length=50), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['response_connector.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['response_policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_decision_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_decision_decided_by_user_id'), ['decided_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_decision_execution_mode'), ['execution_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_decision_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_decision_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_decision_status'), ['status'], unique=False)

    op.create_table('team_api_key_request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=30), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('vote_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_vote_percentage', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('owner_decision', sa.String(length=20), nullable=True),
    sa.Column('owner_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_api_key_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_api_key_request_api_key_id'), ['api_key_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_api_key_request_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_api_key_request_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_api_key_request_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_api_key_request_request_id'), ['request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_api_key_request_requested_by_user_id'), ['requested_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_api_key_request_reviewed_by_user_id'), ['reviewed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_api_key_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_api_key_request_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_api_key_request_team_id'), ['team_id'], unique=False)

    op.create_table('usage_meter',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('credit_type', sa.String(length=30), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('access_method', sa.String(length=20), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('credits_consumed', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_meter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_meter_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meter_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meter_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meter_credit_type'), ['credit_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meter_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meter_measured_at'), ['measured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meter_metric'), ['metric'], unique=False)
        batch_op.create_index('ix_usage_meter_owner_measured', ['owner_user_id', 'measured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meter_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meter_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meter_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meter_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meter_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index('ix_usage_meter_subscription_period', ['subscription_id', 'period_start', 'period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meter_team_id'), ['team_id'], unique=False)

    op.create_table('vulnerability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cve_id', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerability_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_cve_id'), ['cve_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_status'), ['status'], unique=False)

    op.create_table('alert',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alert_type', sa.String(length=150), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_first_seen_at'), ['first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_status'), ['status'], unique=False)

    op.create_table('incident_action',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('response_decision_id', sa.String(length=36), nullable=True),
    sa.Column('triggered_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=150), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt_number >= 1', name='ck_incident_action_attempt_number'),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['response_decision_id'], ['response_decision.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_action_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_action_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_action_response_decision_id'), ['response_decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_action_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_action_triggered_by_user_id'), ['triggered_by_user_id'], unique=False)

    op.create_table('team_api_key_vote',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('voter_user_id', sa.String(length=36), nullable=False),
    sa.Column('vote_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('vote_percentage >= 0 AND vote_percentage <= 100', name='ck_team_api_key_vote_percentage'),
    sa.ForeignKeyConstraint(['request_id'], ['team_api_key_request.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['voter_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'voter_user_id', name='uq_team_api_key_vote')
    )
    with op.batch_alter_table('team_api_key_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_api_key_vote_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_api_key_vote_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_api_key_vote_voter_user_id'), ['voter_user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('access_method', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_access_method'), ['access_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_team_id'), ['team_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('sender_user_id', sa.String(length=36), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('vulnerability_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sound_key', sa.String(length=100), nullable=True),
    sa.Column('action_key', sa.String(length=100), nullable=True),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_sender_user_id'), ['sender_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_vulnerability_id'), ['vulnerability_id'], unique=False)

    op.create_table('incident_note',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('audit_log_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], ),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_note_actor_type'), ['actor_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_note_audit_log_id'), ['audit_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_note_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_note_incident_id'), ['incident_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_note_incident_id'))
        batch_op.drop_index(batch_op.f('ix_incident_note_author_user_id'))
        batch_op.drop_index(batch_op.f('ix_incident_note_audit_log_id'))
        batch_op.drop_index(batch_op.f('ix_incident_note_actor_type'))

    op.drop_table('incident_note')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_vulnerability_id'))
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notification_team_id'))
        batch_op.drop_index(batch_op.f('ix_notification_status'))
        batch_op.drop_index(batch_op.f('ix_notification_sender_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_incident_id'))
        batch_op.drop_index(batch_op.f('ix_notification_event_id'))
        batch_op.drop_index(batch_op.f('ix_notification_alert_id'))

    op.drop_table('notification')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_team_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_incident_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_asset_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_application_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_api_key_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_alert_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_access_method'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('team_api_key_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_api_key_vote_voter_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_api_key_vote_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_api_key_vote_request_id'))

    op.drop_table('team_api_key_vote')
    with op.batch_alter_table('incident_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_action_triggered_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_incident_action_status'))
        batch_op.drop_index(batch_op.f('ix_incident_action_response_decision_id'))
        batch_op.drop_index(batch_op.f('ix_incident_action_incident_id'))
        batch_op.drop_index(batch_op.f('ix_incident_action_action_type'))

    op.drop_table('incident_action')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_status'))
        batch_op.drop_index(batch_op.f('ix_alert_severity'))
        batch_op.drop_index(batch_op.f('ix_alert_origin'))
        batch_op.drop_index(batch_op.f('ix_alert_incident_id'))
        batch_op.drop_index(batch_op.f('ix_alert_first_seen_at'))
        batch_op.drop_index(batch_op.f('ix_alert_event_id'))
        batch_op.drop_index(batch_op.f('ix_alert_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_assigned_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_asset_id'))
        batch_op.drop_index(batch_op.f('ix_alert_application_id'))
        batch_op.drop_index(batch_op.f('ix_alert_alert_type'))

    op.drop_table('alert')
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerability_status'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_severity'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_detected_at'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_cve_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_asset_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_application_id'))

    op.drop_table('vulnerability')
    with op.batch_alter_table('usage_meter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_meter_team_id'))
        batch_op.drop_index('ix_usage_meter_subscription_period')
        batch_op.drop_index(batch_op.f('ix_usage_meter_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_usage_meter_severity'))
        batch_op.drop_index(batch_op.f('ix_usage_meter_period_start'))
        batch_op.drop_index(batch_op.f('ix_usage_meter_period_end'))
        batch_op.drop_index(batch_op.f('ix_usage_meter_owner_user_id'))
        batch_op.drop_index('ix_usage_meter_owner_measured')
        batch_op.drop_index(batch_op.f('ix_usage_meter_metric'))
        batch_op.drop_index(batch_op.f('ix_usage_meter_measured_at'))
        batch_op.drop_index(batch_op.f('ix_usage_meter_environment'))
        batch_op.drop_index(batch_op.f('ix_usage_meter_credit_type'))
        batch_op.drop_index(batch_op.f('ix_usage_meter_asset_type'))
        batch_op.drop_index(batch_op.f('ix_usage_meter_application_id'))
        batch_op.drop_index(batch_op.f('ix_usage_meter_api_key_id'))

    op.drop_table('usage_meter')
    with op.batch_alter_table('team_api_key_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_api_key_request_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_api_key_request_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_team_api_key_request_status'))
        batch_op.drop_index(batch_op.f('ix_team_api_key_request_reviewed_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_api_key_request_requested_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_api_key_request_request_id'))
        batch_op.drop_index(batch_op.f('ix_team_api_key_request_mode'))
        batch_op.drop_index(batch_op.f('ix_team_api_key_request_environment'))
        batch_op.drop_index(batch_op.f('ix_team_api_key_request_application_id'))
        batch_op.drop_index(batch_op.f('ix_team_api_key_request_api_key_id'))

    op.drop_table('team_api_key_request')
    with op.batch_alter_table('response_decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_decision_status'))
        batch_op.drop_index(batch_op.f('ix_response_decision_policy_id'))
        batch_op.drop_index(batch_op.f('ix_response_decision_incident_id'))
        batch_op.drop_index(batch_op.f('ix_response_decision_execution_mode'))
        batch_op.drop_index(batch_op.f('ix_response_decision_decided_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_response_decision_connector_id'))

    op.drop_table('response_decision')
    with op.batch_alter_table('recovery_operation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_operation_status'))
        batch_op.drop_index(batch_op.f('ix_recovery_operation_operation_type'))
        batch_op.drop_index(batch_op.f('ix_recovery_operation_initiated_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_operation_incident_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_operation_actor_type'))

    op.drop_table('recovery_operation')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_verification_mode'))
        batch_op.drop_index(batch_op.f('ix_event_source'))
        batch_op.drop_index(batch_op.f('ix_event_severity'))
        batch_op.drop_index(batch_op.f('ix_event_received_at'))
        batch_op.drop_index(batch_op.f('ix_event_origin'))
        batch_op.drop_index(batch_op.f('ix_event_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_event_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_detection_check'))
        batch_op.drop_index(batch_op.f('ix_event_category'))
        batch_op.drop_index(batch_op.f('ix_event_asset_id'))
        batch_op.drop_index(batch_op.f('ix_event_application_id'))
        batch_op.drop_index('ix_event_application_fingerprint')

    op.drop_table('event')
    with op.batch_alter_table('team_notification_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_notification_rule_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_notification_rule_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_notification_rule_minimum_severity'))
        batch_op.drop_index(batch_op.f('ix_team_notification_rule_enabled'))
        batch_op.drop_index(batch_op.f('ix_team_notification_rule_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_notification_rule_application_id'))

    op.drop_table('team_notification_rule')
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_member_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_member_team_access_enabled'))
        batch_op.drop_index(batch_op.f('ix_team_member_team_access_disabled_until'))
        batch_op.drop_index(batch_op.f('ix_team_member_status'))
        batch_op.drop_index(batch_op.f('ix_team_member_role_id'))

    op.drop_table('team_member')
    with op.batch_alter_table('team_invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invitation_token_hash'))
        batch_op.drop_index(batch_op.f('ix_team_invitation_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_invitation_status'))
        batch_op.drop_index(batch_op.f('ix_team_invitation_role_id'))
        batch_op.drop_index(batch_op.f('ix_team_invitation_invited_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_invitation_expires_at'))
        batch_op.drop_index(batch_op.f('ix_team_invitation_accepted_user_id'))

    op.drop_table('team_invitation')
    with op.batch_alter_table('subscription_application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_application_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_application_status'))
        batch_op.drop_index(batch_op.f('ix_subscription_application_application_id'))

    op.drop_table('subscription_application')
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_status'))
        batch_op.drop_index(batch_op.f('ix_incident_severity'))
        batch_op.drop_index(batch_op.f('ix_incident_opened_at'))
        batch_op.drop_index(batch_op.f('ix_incident_assigned_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_incident_application_id'))

    op.drop_table('incident')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_type'))
        batch_op.drop_index(batch_op.f('ix_asset_status'))
        batch_op.drop_index(batch_op.f('ix_asset_checksum_sha256'))
        batch_op.drop_index(batch_op.f('ix_asset_application_id'))
        batch_op.drop_index(batch_op.f('ix_asset_analysis_status'))

    op.drop_table('asset')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_team_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_status'))
        batch_op.drop_index(batch_op.f('ix_api_key_public_key'))
        batch_op.drop_index(batch_op.f('ix_api_key_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_mode'))
        batch_op.drop_index(batch_op.f('ix_api_key_environment'))
        batch_op.drop_index(batch_op.f('ix_api_key_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_application_id'))

    op.drop_table('api_key')
    with op.batch_alter_table('team_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_role_team_id'))

    op.drop_table('team_role')
    with op.batch_alter_table('team_owner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_owner_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_owner_status'))
        batch_op.drop_index(batch_op.f('ix_team_owner_assigned_by_user_id'))

    op.drop_table('team_owner')
    with op.batch_alter_table('team_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_message_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_message_sender_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_message_reply_to_message_id'))

    op.drop_table('team_message')
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_team_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_status'))
        batch_op.drop_index(batch_op.f('ix_subscription_provider_subscription_reference'))
        batch_op.drop_index(batch_op.f('ix_subscription_plan_code'))
        batch_op.drop_index(batch_op.f('ix_subscription_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_next_billing_at'))
        batch_op.drop_index(batch_op.f('ix_subscription_expires_at'))
        batch_op.drop_index(batch_op.f('ix_subscription_created_by_user_id'))

    op.drop_table('subscription')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_settings_profile_id'))

    op.drop_table('settings')
    with op.batch_alter_table('response_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_policy_team_id'))
        batch_op.drop_index(batch_op.f('ix_response_policy_execution_mode'))
        batch_op.drop_index(batch_op.f('ix_response_policy_enabled'))
        batch_op.drop_index(batch_op.f('ix_response_policy_created_by_user_id'))

    op.drop_table('response_policy')
    with op.batch_alter_table('response_connector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_connector_type'))
        batch_op.drop_index(batch_op.f('ix_response_connector_team_id'))
        batch_op.drop_index(batch_op.f('ix_response_connector_status'))
        batch_op.drop_index(batch_op.f('ix_response_connector_created_by_user_id'))

    op.drop_table('response_connector')
    with op.batch_alter_table('profile_completion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_completion_profile_id'))

    op.drop_table('profile_completion')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_team_id'))
        batch_op.drop_index(batch_op.f('ix_application_status'))
        batch_op.drop_index(batch_op.f('ix_application_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_application_environment'))
        batch_op.drop_index(batch_op.f('ix_application_created_by_user_id'))

    op.drop_table('application')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_status'))
        batch_op.drop_index(batch_op.f('ix_team_slug'))
        batch_op.drop_index(batch_op.f('ix_team_live_access_status'))
        batch_op.drop_index(batch_op.f('ix_team_created_by_user_id'))

    op.drop_table('team')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_status'))
        batch_op.drop_index(batch_op.f('ix_session_session_token_hash'))
        batch_op.drop_index(batch_op.f('ix_session_expires_at'))

    op.drop_table('session')
    with op.batch_alter_table('recovery_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_code_user_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_code_code_hash'))

    op.drop_table('recovery_code')
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_user_id'))

    op.drop_table('profile')
    with op.batch_alter_table('mfa_factor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfa_factor_user_id'))

    op.drop_table('mfa_factor')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_u1_id'))
        batch_op.drop_index(batch_op.f('ix_user_status'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
